# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod 'HYBMasonryAutoCellHeight', '~> 2.0.1'
pod 'UITableView+FDTemplateLayoutCell_Bell', '~> 1.5.0'
target 'PYMasonryLabel' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PYMasonryLabel

  target 'PYMasonryLabelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PYMasonryLabelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
